apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-{{ .Values.ines.name }}
spec:
  hosts:
    - {{ .Values.ines.host }}
  ports:
    - number: 80
      name: http
      protocol: HTTP
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS